### ISSUE TITLE
When using officedown changing from portait to landscape causes problems with page numbering

### ISSUE THREAD

**Issue by jorg03** [davidgohel/officedown#66] opened 2021-04-11 09:50 UTC
I am not sure if my problem is the result of a bug. However, I can reproduce it using the bookdown example included in the package. 

```
dir <- system.file(package = "officedown", "examples", "bookdown")
file.copy(dir, getwd(), recursive = TRUE, overwrite = TRUE)
rmarkdown::render_site("bookdown")
browseURL("bookdown/_book/bookdown.docx")
```

The resulting [bookdown.docx file](https://github.com/davidgohel/officedown/files/6291481/bookdown.docx) shows 10 pages. Word “says” that there are 11 pages. After inserting page numbers using the MS word function, you see that  page 5 (portrait) is followed by page 7 (landscape). Page 6 seems to be missing. If you print or convert the file in pdf, there is now an (empty) page 6 . I have faced the problem always and only when I included pages in landscape using “ “ and “  “. A change from landscape back to portrait does not seem to cause problems.

sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)
officedown_0.2.2

MS Office 365

Kind regards
Jorg

**Comment by davidgohel** [comment] 2021-04-11 14:54
The defined break page type is "oddPage" with BLOCK_LANDSCAPE_STOP.

It's not a bug, this is how Word is working. Page break happen at page 5, the next page is 6, so it restarts at 7. 

Here is an example of how to define specific section settings, you can adapt that example (to landscape section for example) :



````````````

---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE)
library(officedown)
library(officer)
```

```{r}
block_section(prop_section(type = "continuous"))
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu pulvinar arcu,
quis aliquam dui. In at cursus ante. Vestibulum non sagittis lacus. Duis vitae
iaculis dui. Vivamus tempor, nibh ut pretium tempus, enim lorem dignissim quam,
at euismod massa magna at magna. Sed facilisis dapibus diam nec volutpat.
Maecenas facilisis dapibus egestas. Curabitur dignissim pharetra pulvinar. Nunc
bibendum elit sed cursus congue.

`r run_columnbreak()`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu pulvinar arcu,
quis aliquam dui. In at cursus ante. Vestibulum non sagittis lacus. Duis vitae
iaculis dui. Vivamus tempor, nibh ut pretium tempus, enim lorem dignissim quam,
at euismod massa magna at magna. Sed facilisis dapibus diam nec volutpat.
Maecenas facilisis dapibus egestas. Curabitur dignissim pharetra pulvinar. Nunc
bibendum elit sed cursus congue. 

```{r}
block_section(prop_section(
    section_columns = section_columns(widths = c(4,2.5), space = .25, sep = TRUE),
    type = "continuous"))
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu pulvinar arcu,
quis aliquam dui. In at cursus ante. Vestibulum non sagittis lacus. Duis vitae
iaculis dui. Vivamus tempor, nibh ut pretium tempus, enim lorem dignissim quam,
at euismod massa magna at magna. Sed facilisis dapibus diam nec volutpat.
Maecenas facilisis dapibus egestas. Curabitur dignissim pharetra pulvinar. Nunc
bibendum elit sed cursus congue.

````````````


<img width="621" alt="Capture d’écran 2021-04-11 à 16 49 50" src="https://user-images.githubusercontent.com/4331618/114309006-04e1e200-9ae6-11eb-8843-a137d17bf4e7.png">





 I will add this to documentation. (I will close the issue when the doc will be ok).

**Comment by jorg03** [comment] 2021-04-12 20:36
Thanks a lot.
Jörg
Am 11. Apr. 2021, 16:54 +0200 schrieb David Gohel ***@***.***>:

**Comment by davidgohel** [comment] 2021-04-13 08:04
Hi

This is the updated doc: https://ardata-fr.github.io/officeverse/officedown-for-word.html#function-block_section

The last example is an example of landscape section.

**Closed by davidgohel** 2021-04-13 08:04 UTC
