### ISSUE TITLE
demo not compiling correctly

### ISSUE THREAD

**Issue by ammadrigal** [davidgohel/officedown#34] opened 2020-07-09 19:25 UTC
Hello,
I wasn't sure where to ask this question. I'm new to officedown. To test, I tried the instructions in the main page to generate the bookdown.docx demo file. I'm not getting the same result as the output shown. In particular, references don't seem to work and I don't get the tables of  Figures, tables,Contents. Apart from that I'm not getting the nice "Bradley hand" font used in section 5.4 ... I'm guessing the font issue is about a package that I should load with fonts, but I'm not sure about the referencing? I believe I have all it is needed in terms of dependencies of the packages, but I might be missing something? Can't find any extra guidelines in terms of if I need to load any librarys and which order or something... any ideas? help? I'm aware it most be a silly thing on my part.
Thanks

**Comment by ammadrigal** [comment] 2020-07-09 20:03
as extra info: when I tried the minimal word example in the documentation, I get:
Error: read_docx only support docx files

Does this helps to understand the issue I'm having? 

>  # minimal example -----
>   example <- system.file(package = "officedown", "examples/minimal_word.Rmd")
>   rmd_file <- tempfile(fileext = ".Rmd")
>   file.copy(example, to = rmd_file)
>   docx_file_1 <- tempfile(fileext = ".docx")
>   render(rmd_file, output_file = docx_file_1, quiet = TRUE)

**Comment by davidgohel** [comment] 2020-07-09 21:37
The first issue is a duplicate of #22 

If you don't have "Bradley hand", use another one available on your computer or install "Bradley hand"

To install the package, you need to run:

```
install.packages("officedown")
```

The last issue you have is not reproducible, sorry, I can't help there.

**Closed by davidgohel** 2020-07-09 21:37 UTC

**Comment by ammadrigal** [comment] 2020-07-09 22:47
Thanks, I hadn't realised that in order to see the references one needed to refresh the fields (F9) within word. It works now following issue 22!
The last issue happened when running the code you provide in the examples to run the minimal_word.Rmd in your package. I guess it is not reproducible by you because it doesn't throw an error in your machine. Unsure why it is throwing the error in mine.

**Comment by davidgohel** [comment] 2020-07-10 06:29
You have to hit F9 when you changed the default settings of Word. I don't have to do that on my machine, a pop up window is asking me if I do agree to update fields:

> This document contains fields that may refer to other files. Do you want to update the fields in this document?

The last issue is also not happening on 12 different machines maintained by the CRAN: https://cran.r-project.org/web/checks/check_results_officedown.html

Maybe if you followed guidelines (those you deleted when filling that issue) I would be able to help but there I have no idea what code you really ran. 

```
pandoc_available() && pandoc_version() >= numeric_version("2.0")
```
