### ISSUE TITLE
Please bring back the chunk_styled_text function

### ISSUE THREAD

**Issue by alherca73** [davidgohel/officedown#24] opened 2020-06-08 14:50 UTC
Hi there. I have tried to use the Pandoc custom styles. Unfortunately, the bracketed_spans syntax (https://pandoc.org/MANUAL.html#custom-styles) DOES NOT work for me in my Rmarkdown scripts. The fenced_divs syntax DOES work in some cases, not all. It would be great if you could bring back functions such as the "chunk_styled_text" to the Officedown R package. Thanks in advance.

Alex Hernandez

**Comment by davidgohel** [comment] 2020-06-26 12:19
I am trying to understand what DOES NOT work for you

```
---
output: officedown::rdocx_document
---

This is a [formatted text with style StringTok]{custom-style="StringTok"}

::: {custom-style="Author"}
This is a custom paragraph
:::
```


This is producing what I was expecting:

<img width="693" alt="Capture d’écran 2020-06-26 à 14 16 59" src="https://user-images.githubusercontent.com/4331618/85856134-ba41e400-b7b7-11ea-8261-66fbf847b5d0.png">

Can you be more specific about what is not working? Could you provide an example?

Also, what is the result of `rmarkdown::pandoc_version()`?

thanks

**Comment by alherca73** [comment] 2020-06-26 15:37
The first option: 
This is a [formatted text with style StringTok]{custom-style="StringTok"}

**NEVER** works for me. Whenever I try to use a predefined style in my Reference Word Document, what it does is it creates a new style with the same name but it does not customize the text, it is always normal format.

The custom paragraph ALWAYS works.

::: {custom-style="Author"}
This is a custom paragraph
:::

This is what I got
rmarkdown::pandoc_version()
[1] ‘2.7.3’

Thanks for your help.

**Comment by davidgohel** [comment] 2020-06-26 15:45
Thanks

I am really confused because I can not reproduce and my colleague neither.

Could you post an image of the result you are getting?

**Comment by alherca73** [comment] 2020-06-26 16:53
Sure. Thanks. Here are some:

For instance, this shows that it works. I applied a paragraph custom style and it produces what I want:
![Screen Shot 2020-06-26 at 10 49 07 AM](https://user-images.githubusercontent.com/55201378/85881500-f286f980-b79a-11ea-93e5-187132adc0c4.png)
![Screen Shot 2020-06-26 at 10 49 15 AM](https://user-images.githubusercontent.com/55201378/85881531-fe72bb80-b79a-11ea-89d9-785e65cb9081.png)

Here I apply to text within a paragraph and what it does is just creates a new style:

![Screen Shot 2020-06-26 at 10 49 29 AM](https://user-images.githubusercontent.com/55201378/85881617-25c98880-b79b-11ea-850b-d4c4c2e8d621.png)
![Screen Shot 2020-06-26 at 10 49 45 AM](https://user-images.githubusercontent.com/55201378/85881646-31b54a80-b79b-11ea-80c1-e070f488ff56.png)

So, for some reason, only the paragraph option works.

**Comment by alherca73** [comment] 2020-06-26 18:00
It looks like if I used one of the pre-defined styles in the Word document reference, then it DOES work. However, when I try to add a completely NEW style, and try to use it in the *.RMD it does NOT work. Not sure what are the requirements of new styles in the word document reference to work. For now I guess I can use some of the predefined styles.
Thanks.

**Comment by davidgohel** [comment] 2020-06-29 12:35
thanks,

The style you are using are supposed to exist in the template (or the default pandoc template). That why you had the impression it does not work. You can save styles in a Word document and reuse them by using `reference-doc` argument.

I am closing that issue as it is related to pandoc usage.

**Closed** 2020-06-29 12:35 UTC
